version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: cryptovault-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cryptovault

  server:
    build: ./server
    container_name: cryptovault-api
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cryptovault
      - JWT_SECRET=cryptovault_super_secret_jwt_key_2024
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped

  client:
    build: ./client
    container_name: cryptovault-web
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo_data:
